import NavBar from '@/components/NavBar'
import './globals.css'
import { Quicksand } from 'next/font/google'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href={`https://fonts.googleapis.com/css?family=Quicksand`} rel="stylesheet"/>
        <link href={`https://fonts.googleapis.com/css?family=Axiforma`} rel="stylesheet"/>
      </head>
      <body className={quicksand.className}>
        <div className='h-screen'>
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  )
}